### ISSUE TITLE
Refactor Application Behavior to Improve Modularity and Maintainability

### ISSUE THREAD

**Issue by cristianMarcial** [Yamil-Serrano/Zypher#1]
# Task: Refactor Application Behavior to Improve Modularity and Maintainability

## Description  
Currently, the application logic is tightly coupled across multiple modules, making it difficult to modify specific behaviors without affecting other parts of the code. The current structure is as follows:

- **main/UI**: Contains the logic for creating the application window and managing the Tkinter event loop.
- **scraper**: Holds the logic for scraping data from the YouTube platform.
- **miscellaneous**: Contains various utility functions or miscellaneous logic.

The **main** and **UI** modules are coupled together because Tkinter's event loop is initiated within the same module. This results in a scattered architecture, where any changes to the behavior of the application require modifications across different parts of the codebase.

## Objective  
Refactor the code to improve the separation of concerns and modularity. The goal is to:
- Isolate the application's behavior so that specific functionalities can be modified without affecting unrelated modules.
- Make the system more maintainable by creating clear boundaries between different parts of the application (e.g., UI, scraper, utilities).
- Minimize dependencies between modules to simplify debugging, testing, and further development.

## Proposed Actions  
1. Refactor the **UI** module to handle only the user interface logic and delegate business logic to other modules.
2. Move the logic for creating and managing the Tkinter event loop into a separate module if needed to maintain clarity.
3. Improve the **scraper** module to handle only the data scraping functionality and ensure it is decoupled from UI and other parts of the application.
4. Organize the **miscellaneous** module for utility functions that are shared across the application, ensuring no cross-module dependencies unless necessary.
5. Ensure each module has a clear and well-defined responsibility (single responsibility principle).
6. Update the documentation to reflect the changes in the modular architecture.

## Expected Outcome  
By refactoring the application, we will create a more maintainable and extensible codebase, making it easier to introduce changes and new features without risk of breaking existing functionality. This will also make future collaboration more efficient by improving clarity and reducing module interdependencies.

**Comment by Yamil-Serrano** [comment]
I have separated the code into two modules, main.py and user_interface.py, currently I merged the branch to main.

**Comment by Yamil-Serrano** [comment]
I have refactored the code by separating it into two distinct modules: main.py and user_interface.py. After implementing the changes, I have successfully merged the feature branch into the main branch.
